### ISSUE TITLE
Create UI for mediation Timer screen -- as seen on the figma link

### ISSUE THREAD

**Issue by fiizzy** [fiizzy/MentalWaev#3]
- [ ] create UI matching the figma design
- [ ] writes tests if necessary ( optional )

**Comment by sobuur0** [comment]
Hello @fiizzy .
If no one has started this task, you could assign it to me.
I'd like to implement this

**Comment by fiizzy** [comment]
heyy @t-bolt , Nobody is working on this task yet. So you can proceed with that. I just assigned you to it! :)
